### ISSUE TITLE
backtest() works, but backtest_many() gives MemoryError

### ISSUE THREAD

**Issue by quant5** [cvxgrp/cvxportfolio#177]
## Specifications
Windows machine (x86). Python 3.11.5.
Fresh install of cvxportfolio to the new version (1.3.2) from a fresh virtual environment.
![image](https://github.com/user-attachments/assets/6644f392-dbcc-47c0-8bcd-6cb6991f8e94)

## Description
I try to run the hello_world.py file here: https://github.com/cvxgrp/cvxportfolio/blob/master/examples/hello_world.py
* the script gets data correctly and the data files are fine.
* the script fails on `simulator.backtest_many([policy, cvx.Uniform()], start_time="2020-01-01")`:
  * this is very strange since my machine is quite large (64gb RAM) and the memory allocation in the error is only 1mb.

![image](https://github.com/user-attachments/assets/95c5db66-a4d2-4df9-bd1b-4a75fc88caf7)

* If I replace backtest_many with simple `backtest(), script succeeds. Example: `simulator.backtest(policy, start_time="2020-01-01")` or `simulator.backtest(cvx.Uniform(), start_time="2020-01-01")`

### Other remarks

* Switching the solver to something else e.g., "ECOS" or "CLARABEL" did not fix the issue.
* Downgrading numpy to 1.5.x did not fix the issue.
* Task manager does not indicate any huge spike in memory use.
* The test suite (e.g., `python -m cvxportfolio.tests`) worked fine. (see below)
![image](https://github.com/user-attachments/assets/5beb0d23-dee3-461b-8a6b-5806f025a215)

My thought is that `multiprocess` compatibility with Numpy could be the issue? But not seeing anything from a quick search. Any help would be appreciated.

**Comment by enzbus** [comment]
Thanks for reporting this. Yes, it looks like an incompatibility between `multiprocess` and something on your system. Looks like you're on Windows; in the worst case you can try to switch to a Linux virtual machine. I'll work on adding an option to revert to using standard Python `multiprocessing`, since a few releases ago `multiprocess` is not necessary any more, but I left it because it looked more robust. Can you try in the next ~24hrs if a patch that drops `multiprocess` from the dependencies and moves it to an optional dependency (if installed, use it, otherwise no) fixes this issue for you? PS I assume everything works fine if you set `parallel=False` in the default options to `backtest_many`...

**Comment by enzbus** [comment]
Ok, working on it in PR #178

**Comment by enzbus** [comment]
Looks like the fix passes tests, I'm going to merge and then you can try by installing the development version (https://www.cvxportfolio.com/en/master/#advanced-install-development-version); not sure which environment manager you're using but the syntax should be similar to `pip`'s. It's rather strange, I had made a test case specifically for multiprocessing; maybe it passes because GitHub only provides single-processor test runners? Let me merge and we see.

**Comment by enzbus** [comment]
Ok, in any case I've merged (always good to minimize dependencies, `multiprocess` was there for advanced usecases, like custom forecasters using difficult third party libraries).

**Comment by enzbus** [comment]
Just a thought. Perhaps @quant5 you have some Windows-specific
limit on processes spawned by a master process? Could be that GutHub test runners are sanitized against this sort of things. I recently found out new versions of MacOS have all sorts of limits on "unsigned" codes and you need to manually unset a bunch of code attributes to get many open source codes running. In any case I'm happy with having dropped a depencency :)
