### ISSUE TITLE
Hello World example

### ISSUE THREAD

**Issue by Weesper1985** [cvxgrp/cvxportfolio#7]
Hi,

I went through the "Hello World" example via Jupyter notebook, but when defining SPO policy it does not  recognize "return_forecast". After leaving this parameter out it says that the "alpha_model" needs to be given. I assumed that this is the same parameter as "return_forecast" and assigned "r_hat"  to it, but this gives an AssertionError. Could you kindly tell me whether something has changed to the policy parameters? 

NB - it seems the policies.py for the stand-alone module (v. 0.02 installed) differs from the policies.py on GitHub, which might be causing this issue.

Many thanks & best regards,

Mike Kraus

**Comment by enzobusseti** [comment]
Mike

the issue has been fixed in the repo, and I just updated the version in pypi (i.e., pip). In general, I recommend using the repo directly:

`git clone  https://github.com/cvxgrp/cvxportfolio.git`
`cd cvxportfolio`
`conda env create -f test_environment.yml`
`source activate cvxportfolio-testing`
`jupyter notebook`

and then run the examples. you can also install the package with 
`python setup.py install`
