### ISSUE TITLE
poetry for dependency management

### ISSUE THREAD

**Issue by quant9** [cvxgrp/cvxportfolio#83]
Many modern repos use of Poetry over the current combination of venv + requirements.txt for dependency management (especially as the current requirements file does not specify versions).

Let me know if that sounds like a good idea; if so, I will create a branch.

Some good resources for migrating to poetry vs venv:
https://blog.mathieu-leplatre.info/tips-for-your-makefile-with-python.html
https://github.com/mozilla-services/telescope/pull/752/files

**Comment by quant9** [comment]
One of the issues I am running into when running `make` is that on Windows (which I use) the python path is not `env/bin/python` but `env/Scripts/python`. 
https://stackoverflow.com/questions/43826134/why-is-the-bin-directory-named-differently-scripts-on-windows

**Comment by enzbus** [comment]
Thanks for catching the issue with the Makefile on windows! I'll merge it. (We test against windows currently via github integration, we use the Makefile there and it all works, weird.) We used poetry in one or two releases (thanks to @tschm 's contribution) but I decided to revert to setup.py for simplicity and because it is still the most used deployment mechanism. I don't plan to ever include extension modules in cvxportfolio so PEP517/8 don't apply here. My understanding is that venv and pip provide all functionalities you'd get from poetry and they're both part of the Python standard library. Also it's nice to keep the environment directory in the repository directory (poetry stores environments in some system-dependent location). This all applies to developers, for users we want the least complicated experience, and pip install (without PEP517/8) is the most supported way. (There are bugs that emerge in various packages when PEP517/8 is enforced, but are not there otherwise.) Also you don't have to use the Makefile and are free to use poetry locally if you want. In fact, if you do, you may catch more bugs and report them, as poetry tends to update all packages to the latest version.

**Comment by enzbus** [comment]
Also, `requirements.txt` is only used in the Makefile, those are not the cvxportfolio package dependecies. Dependecies are in `setup.py`, `requirements.txt` only specifies the development environment.

**Comment by quant9** [comment]
Thanks for the discussion - I respect the decision to keep venv / pip.
Versioning remains unhandled - is that by design, does it make sense to use at least carat logic to specify versions?

**Comment by enzbus** [comment]
Another good point. This is a work in progress in fact. My goal is to use only very common parts of the APIs of the dependencies so that any version (apart from very old ones) would work. The idea is that it should be super easy to add cvxportfolio to an existing environment without forcing upgrades (or downgrades!). I'm planning to set in the github integration test matrix some old versions of the various packages just to be sure (really only cvxpy and yfinance because the other three are mature enough). I'm keeping pandas usage to the bare minimum (they are famous for breaking little-used parts of their API). In any case any Python environment is different and so the recommended process when integrating cvxportfolio is to run the unittest suite (which we ship with the pip package) and report here any issue. If you set up an environment from scratch, instead, you'll probably have the newest version of each, and so everything should work because we test it with every git push. But it's important to have the lowest cost when integrating it in an existing environment.

**Comment by tschm** [comment]
@enzbus I won't be able to help you here. Such a package should not care about a package such as finance. Keep the data fetching orthogonal to your problems. Of course, poetry can store the entire virtual environment in the local folder and the problems of pip to replicate environments exactly on different machine let to the development of poetry. However, let's not waste time on pip vs poetry here. I have created a .github repo for the team here which makes some workflows really simple. For a complete example please have a look at https://github.com/cvxgrp/simulator. I am also not sure you have ever seen poetry build in practice. It does compile a setup.py for you. The user of your package is not supposed to have poetry installed.
