### ISSUE TITLE
Dollar volume assumption

### ISSUE THREAD

**Issue by quant9** [cvxgrp/cvxportfolio#95]
This is a more open question, but I noticed the dollar-volume assumption is:

```
data["ValueVolume"] = data["Volume"] * data["Open"]
```

Would it be more accurate / widely accepted to use (Open + Close / 2) instead of just the Open?

**Comment by enzbus** [comment]
Hello! valid point. The definition of volume in value units I'm using seems a bit arbitrary. The correct one would use the volume-weighted average price (VWAP): the sum, over the period, of each trade in number of shares times its transaction price, divided divided by the sum over the period of the number of shares traded. Then, ``ValueVolume = Volume * VWAP``. Of course that can't be computed unless one has access to tick data, which is way beyond the level of complexity I'm targeting here. Any other definition is a first-order approximation of the correct one (see, *e.g.*, https://stanford.edu/~boyd/papers/pdf/vwap_opt_exec.pdf ).

I guess my definition has the merit of simplicity since it only uses one element of the open-high-low-close dataframe. (You could as well argue that ``(Open + Close + High + Low)/4`` is  a better one.) Also, since in the book we focus on open prices only (in fact, abstracting away the concept of close, high, and low prices) this seems more consistent. In many settings (like continuous markets, take ``BTC-USD`` on 1-minute periods) you wouldn't care about close prices in fact, and only need to keep track of one price array and one volume array, both sampled at the start of each period.

However, I promise that by the time we release a stable version, decisions such as this one will be easy to override by defining a different data accessor, without having to patch the source code itself.
